datasources:
  sensors:
    type: "mongo"
    host: "localhost"
    database: "sensor"
    port: 27017
    collection: "readings"
    auth_mechanism: "&authSource=admin&authMechanism=SCRAM-SHA-1"
  feedbacks:
    type: "firebase"
    collection: "feedback"

dask:
  scheduler_url: "tcp://127.0.0.1:8786"
