version: "3.3"

services:
  mongodb:
    container_name: mongo

    image: mongo:5
    volumes:
      - ./conf/mongo/conf/mongod.conf:/etc/mongod.conf
      - ./conf/mongo/script:/docker-entrypoint-initdb.d
      - ./data/mongo-datadir:/data/db
      - ./data/mongo-log:/var/log/mongodb/
    ports:
      - 27017:27017

  # to visualize mongodb content:
  mongo-express:
    container_name: mongo-express
    
    image: mongo-express:latest
    restart: always
    depends_on:
      - mongodb
    ports:
      - 8081:8081

  dask-scheduler:
    container_name: scheduler

    image: ghcr.io/dask/dask
    restart: always
    entrypoint: dask-scheduler  # start scheduler
    ports:
      - 8787:8787
      - 8786:8786
    expose:
      - 8786
      
  dask-worker-1:
    container_name: worker1

    image: ghcr.io/dask/dask
    restart: always
    depends_on:
      - dask-scheduler
    entrypoint: dask-worker scheduler:8786 # start worker

  dask-worker-2:
    container_name: worker2

    image: ghcr.io/dask/dask
    restart: always
    depends_on:
     - dask-scheduler
    entrypoint: dask-worker scheduler:8786 # start worker

  dask-worker-3:
    container_name: worker3

    image: ghcr.io/dask/dask
    restart: always
    depends_on:
     - dask-scheduler
    entrypoint: dask-worker scheduler:8786 # start worker

# using the default network. all the containers are discoverable in a host with the container name
